package com.thisapp.databasepelanggan.database

class Config {

    companion object {
        const val DATABASE_NAME = "DaatabasePelanggan.db"
        const val DATABASE_VERSION = 2
        const val TABLE_NAME = "DataPelanggan"
        const val COLUMN_ID_DATABASE = "ID_DATABASE"
        const val COLUMN_NAME = "NAMA"
        const val COLUMN_ADDRESS = "ALAMAT"
        const val COLUMN_PHONE_NUMBER = "PHONE_NUMBER"
        const val COLUMN_EMAIL_ADDRESS = "ALAMAT_EMAIL"
        const val COLUMN_KETERANGAN = "KETERANGAN"
        const val COLUMN_PRODUCT_NAME = "NAMA_PRODUK"
        const val COLUMN_PRODUCT_PRICE = "HARGA_PRODUK"
        const val TABLE_PRODUCT = "PRODUK"
        const val TABLE_CATATAN = "CATATAN"
        const val COLUMN_CUSTOMER_NAME = "NAMA_PELANGGAN"
        const val COLUMN_DATE = "TANGGAL_PESAN"
        const val COLUMN_TIME = "JAM_PESAN"
        const val COLUMN_STATUS_PEMBAYARAN= "STATUS_PEMBAYARAN"
        const val COLUMN_KET = "KETERANGAN_CATATAN"
        const val TABLE_ITEM = "ITEM"
        const val COLUMN_IEM_NAME ="NAMA_PRODUK_ITEM"
        const val COLUMN_ITEM_QUANTITY = "JUMLAH_PRODUK_ITEM"
        const val COLUMN_ITEM_CATATAN_CUSTOMER_NAME = "CATATAN_CUSTOMER_NAME"
        const val CREATE_TABLE = "CREATE TABLE IF NOT EXISTS "+ TABLE_NAME+"("+ COLUMN_ID_DATABASE+
                " INTEGER PRIMARY KEY AUTOINCREMENT, "+ COLUMN_NAME+" TEXT NOT NULL, "+
                COLUMN_ADDRESS+" TEXT, "+ COLUMN_PHONE_NUMBER+" TEXT, "+ COLUMN_EMAIL_ADDRESS+" TEXT, "+
                COLUMN_KETERANGAN+" TEXT);"
        const val CREATE_TABLE_PRODUCT = "CREATE TABLE IF NOT EXISTS "+ TABLE_PRODUCT+
                "("+ COLUMN_ID_DATABASE+" INTEGER PRIMARY KEY AUTOINCREMENT, "+ COLUMN_PRODUCT_NAME+
                " TEXT NOT NULL, "+ COLUMN_PRODUCT_PRICE+" REAL NOT NULL);"
        const val CREATE_TABLE_CATATAN = "CREATE TABLE IF NOT EXISTS "+ TABLE_CATATAN+
                " ("+ COLUMN_ID_DATABASE+" INTEGER PRIMARY KEY AUTOINCREMENT, "+ COLUMN_CUSTOMER_NAME+
                " TEXT NOT NULL, "+ COLUMN_DATE+" TEXT NOT NULL, "+ COLUMN_TIME+" TEXT NOT NULL, "+
                COLUMN_STATUS_PEMBAYARAN+" TEXT NOT NULL, "+ COLUMN_KET+" TEXT NOT NULL);"
        const val CREATE_TABLE_ITEM = "CREATE TABLE IF NOT EXISTS "+ TABLE_ITEM+" ("+
                COLUMN_ID_DATABASE+" INTEGER PRIMARY KEY AUTOINCREMENT, "+ COLUMN_IEM_NAME+
                " TEXT NOT NULL, "+ COLUMN_ITEM_QUANTITY+" INTEGER NOT NULL, "+
                COLUMN_ITEM_CATATAN_CUSTOMER_NAME+" TEXT NOT NULL);"
        const val DROP_TABLE = "DROP TABLE IF EXISTS "+ TABLE_NAME
        const val DROP_TABLE_PRODUCT = "DROP TABLE IF EXISTS "+ TABLE_PRODUCT
        const val DROP_TABLE_CATATAN = "DROP TABLE IF EXISTS "+ TABLE_CATATAN
        const val DROP_TABLE_ITEM = "DROP TABLE IF EXISTS "+ TABLE_ITEM

    }
}